#!/usr/bin/env python3
"""Synchronize generated Codex mirrors from canonical Claude harness sources."""
from __future__ import annotations
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
MARK = "<!-- GENERATED by scripts/harness/sync_agent_harness.py; edit canonical .claude sources, never this file. -->\n"
TOML_MARK = "# GENERATED by scripts/harness/sync_agent_harness.py; edit canonical .claude sources, never this file.\n"
READ_ONLY = {"verifier", "qa-judge", "security-reviewer"}

def norm(value: str) -> str:
    return value.replace("\r\n", "\n").replace("\r", "\n")

def read(path: Path) -> str:
    return norm(path.read_text(encoding="utf-8"))

def parse_frontmatter(path: Path) -> tuple[dict[str, str], str]:
    text = read(path)
    if not text.startswith("---\n"):
        raise ValueError(f"{path}: missing YAML frontmatter")
    end = text.find("\n---\n", 4)
    if end < 0:
        raise ValueError(f"{path}: unterminated YAML frontmatter")
    meta: dict[str, str] = {}
    for line in text[4:end].splitlines():
        if not line or line.lstrip().startswith("#"):
            continue
        if ":" not in line:
            raise ValueError(f"{path}: invalid frontmatter line")
        key, value = line.split(":", 1)
        meta[key.strip()] = value.strip().strip('"').strip("'")
    missing = {"name", "description", "model", "effort"} - meta.keys()
    if missing:
        raise ValueError(f"{path}: missing frontmatter {', '.join(sorted(missing))}")
    return meta, text[end + 5:]

def role_toml(src: Path) -> tuple[str, str]:
    meta, body = parse_frontmatter(src)
    name = meta["name"]
    if src.stem != name:
        raise ValueError(f"{src}: name must match filename")
    if meta["model"] != "claude-opus-5-5" or meta["effort"] not in {"medium", "high"}:
        raise ValueError(f"{src}: unsupported role model or effort")
    if "'''" in body:
        raise ValueError(f"{src}: developer instructions contain unsupported TOML literal delimiter")
    lines = [TOML_MARK.rstrip(), f"name = {json.dumps(name)}", f"description = {json.dumps(meta['description'])}", 'model = "gpt-6.1-sol"', f'model_reasoning_effort = {json.dumps(meta["effort"])}']
    if name in READ_ONLY:
        lines.append('sandbox_mode = "read-only"')
    lines.extend(["developer_instructions = '''", body.rstrip("\n"), "'''", ""])
    return name, "\n".join(lines)

def expected():
    yield ROOT / "AGENTS.md", MARK + read(ROOT / ".codex/AGENTS.header.md") + "\n" + read(ROOT / "CLAUDE.md")
    skills = ROOT / ".claude/skills"
    for src in sorted(p for p in skills.rglob("*") if p.is_file()):
        value = read(src)
        if src.name == "SKILL.md":
            value = MARK + value
        yield ROOT / ".agents/skills" / src.relative_to(skills), value
    for src in sorted((ROOT / ".claude/agents").glob("*.md")):
        name, value = role_toml(src)
        yield ROOT / ".codex/agents" / f"{name}.toml", value

def write(path: Path, value: str) -> None:
    value = norm(value)
    if not path.exists() or read(path) != value:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(value, encoding="utf-8", newline="\n")

def clean_orphans(items) -> None:
    wanted = {path.resolve() for path, _ in items}
    for base in (ROOT / ".agents/skills", ROOT / ".codex/agents"):
        if not base.exists():
            continue
        for path in sorted((p for p in base.rglob("*") if p.is_file()), reverse=True):
            if path.resolve() not in wanted:
                path.unlink()
        for path in sorted((p for p in base.rglob("*") if p.is_dir()), reverse=True):
            if not any(path.iterdir()):
                path.rmdir()

def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--if-stale", action="store_true")
    parser.add_argument("--quiet", action="store_true")
    args = parser.parse_args()
    try:
        items = list(expected())
    except (OSError, ValueError) as exc:
        print(f"sync failed: {exc}")
        return 2
    stale = [str(path.relative_to(ROOT)) for path, value in items if not path.exists() or read(path) != norm(value)]
    wanted = {path.resolve() for path, _ in items}
    for base in (ROOT / ".agents/skills", ROOT / ".codex/agents"):
        if base.exists():
            stale.extend(str(p.relative_to(ROOT)) for p in base.rglob("*") if p.is_file() and p.resolve() not in wanted)
    if args.check:
        if stale:
            if not args.quiet:
                print("stale generated files: " + ", ".join(sorted(stale)))
            return 1
        if not args.quiet:
            print("harness mirrors current")
        return 0
    if args.if_stale and not stale:
        return 0
    for path, value in items:
        write(path, value)
    clean_orphans(items)
    if not args.quiet:
        print("harness mirrors synchronized")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
